TRAIN:
  ENABLE: False
  DATASET: charades
  BATCH_SIZE: 4
  EVAL_PERIOD: 6
  CHECKPOINT_PERIOD: 6
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: "D:/yzx/SlowFast/tools/logs/slowfast1/checkpoints/checkpoint_epoch_00006.pyth"
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 256]
  TRAIN_CROP_SIZE: 256
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  MULTI_LABEL: True
  RANDOM_FLIP: True
  SSL_COLOR_JITTER: True

  INV_UNIFORM_SAMPLE: True
  ENSEMBLE_METHOD: max
  REVERSE_INPUT_CHANNEL: True
  PATH_TO_DATA_DIR: "G:/yzx/uav-kabr/KABR/KABR/annotation"
  PATH_PREFIX: "G:/yzx/uav-kabr/KABR/KABR/dataset/image"
#  PATH_TO_DATA_DIR: "C:\\Users\\zyq\\Desktop\\ava\\annotations"
#  PATH_PREFIX: "C:\\Users\\zyq\\Desktop\\ava\\rawframes"
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  NORM_TYPE: sync_batchnorm
  NUM_SYNC_DEVICES: 1
SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01, 0.001, 0.0001, 0.00001]
  STEPS: [0, 41, 49]
  MAX_EPOCH: 41
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 3.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 8
  ARCH: slowfast
  LOSS_FUNC: bce_logit
  HEAD_ACT: sigmoid
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: charades
  BATCH_SIZE: 4
  NUM_ENSEMBLE_VIEWS: 2
  NUM_SPATIAL_CROPS: 1
#  CHECKPOINT_FILE_PATH: "D:/yzx/SlowFast/tools/logs/slowfast1/checkpoints/checkpoint_epoch_00006.pyth"

DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True

NUM_GPUS:
  1

NUM_SHARDS:
  1

RNG_SEED:
  0

OUTPUT_DIR: ./logs/slowfast1

LOG_MODEL_INFO: True

DEMO:
  ENABLE: True
  LABEL_FILE_PATH:  "D:/yzx/SlowFast/demo/charadas/classes.json"


  #WEBCAM: 0

  INPUT_VIDEO: "C:\\Users\\zyq\\Desktop\\output_video.mp4"
  OUTPUT_FILE: "D:/yzx/SlowFast/demo/charadas/out.mp4"