# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin2(object):
    def setupUi(self, Formwin2):
        Formwin2.setObjectName("Formwin2")
        Formwin2.resize(644, 376)
        self.label_daichuli = QtWidgets.QLabel(Formwin2)
        self.label_daichuli.setGeometry(QtCore.QRect(20, 30, 301, 171))
        self.label_daichuli.setFrameShape(QtWidgets.QFrame.Box)
        self.label_daichuli.setText("")
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin2)
        self.label_jieguo.setGeometry(QtCore.QRect(320, 30, 311, 171))
        self.label_jieguo.setFrameShape(QtWidgets.QFrame.Box)
        self.label_jieguo.setText("")
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin2)
        self.pushButton_load.setGeometry(QtCore.QRect(20, 210, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin2)
        self.pushButton_save.setGeometry(QtCore.QRect(210, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_fun0 = QtWidgets.QPushButton(Formwin2)
        self.pushButton_fun0.setGeometry(QtCore.QRect(20, 250, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_fun0.setFont(font)
        self.pushButton_fun0.setObjectName("pushButton_fun0")
        self.pushButton_fun1 = QtWidgets.QPushButton(Formwin2)
        self.pushButton_fun1.setEnabled(False)
        self.pushButton_fun1.setGeometry(QtCore.QRect(20, 290, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_fun1.setFont(font)
        self.pushButton_fun1.setObjectName("pushButton_fun1")
        self.pushButton_fun2 = QtWidgets.QPushButton(Formwin2)
        self.pushButton_fun2.setEnabled(False)
        self.pushButton_fun2.setGeometry(QtCore.QRect(20, 330, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_fun2.setFont(font)
        self.pushButton_fun2.setObjectName("pushButton_fun2")
        self.jieguo = QtWidgets.QTextBrowser(Formwin2)
        self.jieguo.setGeometry(QtCore.QRect(360, 210, 271, 151))
        self.jieguo.setObjectName("jieguo")

        self.retranslateUi(Formwin2)
        QtCore.QMetaObject.connectSlotsByName(Formwin2)

    def retranslateUi(self, Formwin2):
        _translate = QtCore.QCoreApplication.translate
        Formwin2.setWindowTitle(_translate("Formwin2", "Form"))
        self.pushButton_load.setText(_translate("Formwin2", "Choose Picture"))
        self.pushButton_save.setText(_translate("Formwin2", "Save Picture"))
        self.pushButton_fun0.setText(_translate("Formwin2", "Detection"))
        self.pushButton_fun1.setText(_translate("Formwin2", "Tracking"))
        self.pushButton_fun2.setText(_translate("Formwin2", "Behavior Recognition"))
