# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin4(object):
    def setupUi(self, Formwin4):
        Formwin4.setObjectName("Formwin4")
        Formwin4.resize(646, 388)
        self.label_daichuli = QtWidgets.QLabel(Formwin4)
        self.label_daichuli.setGeometry(QtCore.QRect(20, 30, 301, 171))
        self.label_daichuli.setFrameShape(QtWidgets.QFrame.Box)
        self.label_daichuli.setText("")
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin4)
        self.label_jieguo.setGeometry(QtCore.QRect(320, 30, 311, 171))
        self.label_jieguo.setFrameShape(QtWidgets.QFrame.Box)
        self.label_jieguo.setText("")
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin4)
        self.pushButton_load.setGeometry(QtCore.QRect(20, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin4)
        self.pushButton_save.setGeometry(QtCore.QRect(260, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_d0 = QtWidgets.QPushButton(Formwin4)
        self.pushButton_d0.setGeometry(QtCore.QRect(20, 250, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_d0.setFont(font)
        self.pushButton_d0.setObjectName("pushButton_d0")
        self.pushButton_d1 = QtWidgets.QPushButton(Formwin4)
        self.pushButton_d1.setGeometry(QtCore.QRect(20, 290, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_d1.setFont(font)
        self.pushButton_d1.setObjectName("pushButton_d1")
        self.pushButton_d2 = QtWidgets.QPushButton(Formwin4)
        self.pushButton_d2.setGeometry(QtCore.QRect(20, 330, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_d2.setFont(font)
        self.pushButton_d2.setObjectName("pushButton_d2")
        self.pushButton_stop = QtWidgets.QPushButton(Formwin4)
        self.pushButton_stop.setGeometry(QtCore.QRect(140, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setItalic(True)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.jieguo_2 = QtWidgets.QTextBrowser(Formwin4)
        self.jieguo_2.setGeometry(QtCore.QRect(370, 210, 261, 151))
        self.jieguo_2.setObjectName("jieguo_2")

        self.retranslateUi(Formwin4)
        QtCore.QMetaObject.connectSlotsByName(Formwin4)

    def retranslateUi(self, Formwin4):
        _translate = QtCore.QCoreApplication.translate
        Formwin4.setWindowTitle(_translate("Formwin4", "Form"))
        self.pushButton_load.setText(_translate("Formwin4", "Choose"))
        self.pushButton_save.setText(_translate("Formwin4", "Save"))
        self.pushButton_d0.setText(_translate("Formwin4", "Detection"))
        self.pushButton_d1.setText(_translate("Formwin4", "Tracking"))
        self.pushButton_d2.setText(_translate("Formwin4", "Behavior Recognition"))
        self.pushButton_stop.setText(_translate("Formwin4", "Stop"))
