# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 591)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.Func_1 = QtWidgets.QPushButton(self.groupBox)
        self.Func_1.setGeometry(QtCore.QRect(10, 30, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(False)
        self.Func_1.setFont(font)
        self.Func_1.setObjectName("Func_1")
        self.Func_2 = QtWidgets.QPushButton(self.groupBox)
        self.Func_2.setGeometry(QtCore.QRect(100, 30, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(False)
        self.Func_2.setFont(font)
        self.Func_2.setObjectName("Func_2")
        self.Func_3 = QtWidgets.QPushButton(self.groupBox)
        self.Func_3.setGeometry(QtCore.QRect(190, 30, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(False)
        self.Func_3.setFont(font)
        self.Func_3.setObjectName("Func_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 40, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 40, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 40, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.Dis_vid = QtWidgets.QLabel(self.centralwidget)
        self.Dis_vid.setGeometry(QtCore.QRect(310, 90, 591, 401))
        self.Dis_vid.setFrameShape(QtWidgets.QFrame.Box)
        self.Dis_vid.setText("")
        self.Dis_vid.setObjectName("Dis_vid")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(700, 90, 201, 401))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(True)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: rgb(0, 0,0); background-color: rgb(255, 255,255,0.7)")
        self.textEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit.setObjectName("textEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 281, 431))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.speed_1 = QtWidgets.QLabel(self.groupBox_2)
        self.speed_1.setGeometry(QtCore.QRect(10, 30, 261, 131))
        self.speed_1.setFrameShape(QtWidgets.QFrame.Box)
        self.speed_1.setText("")
        self.speed_1.setObjectName("speed_1")
        self.speed_2 = QtWidgets.QLabel(self.groupBox_2)
        self.speed_2.setGeometry(QtCore.QRect(10, 160, 261, 131))
        self.speed_2.setFrameShape(QtWidgets.QFrame.Box)
        self.speed_2.setText("")
        self.speed_2.setObjectName("speed_2")
        self.speed_3 = QtWidgets.QLabel(self.groupBox_2)
        self.speed_3.setGeometry(QtCore.QRect(10, 290, 261, 131))
        self.speed_3.setFrameShape(QtWidgets.QFrame.Box)
        self.speed_3.setText("")
        self.speed_3.setObjectName("speed_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(760, 40, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(920, 40, 261, 461))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setItalic(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.PD_1 = QtWidgets.QLabel(self.groupBox_3)
        self.PD_1.setGeometry(QtCore.QRect(20, 30, 231, 131))
        self.PD_1.setFrameShape(QtWidgets.QFrame.Box)
        self.PD_1.setText("")
        self.PD_1.setObjectName("PD_1")
        self.PD_2 = QtWidgets.QLabel(self.groupBox_3)
        self.PD_2.setGeometry(QtCore.QRect(20, 160, 231, 141))
        self.PD_2.setFrameShape(QtWidgets.QFrame.Box)
        self.PD_2.setText("")
        self.PD_2.setObjectName("PD_2")
        self.PD_3 = QtWidgets.QLabel(self.groupBox_3)
        self.PD_3.setGeometry(QtCore.QRect(20, 300, 231, 141))
        self.PD_3.setFrameShape(QtWidgets.QFrame.Box)
        self.PD_3.setText("")
        self.PD_3.setObjectName("PD_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Function Tools"))
        self.Func_1.setText(_translate("MainWindow", "Species"))
        self.Func_2.setText(_translate("MainWindow", "Tracking"))
        self.Func_3.setText(_translate("MainWindow", "Behavior"))
        self.pushButton.setText(_translate("MainWindow", "Video"))
        self.pushButton_2.setText(_translate("MainWindow", "Picture"))
        self.pushButton_3.setText(_translate("MainWindow", "Camera"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:italic;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Animal Id:             1</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Species Name:       Zebra</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Behavior Type:      Walk</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Speed:                   0.2322</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  GPS:             0.43659628</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                      36.86873040</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Animal Id:             2</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Species Name:       Zebra</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Behavior Type:      Walk</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Speed:                   0.2322</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  GPS:             0.43659628</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                      36.86873040</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Animal Id:             3</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Species Name:       Zebra</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Behavior Type:      Walk</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Speed:                   0.2322</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  GPS:              0.43659628</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">                        36.86873040</p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Speed and Time"))
        self.pushButton_4.setText(_translate("MainWindow", "Save"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Population Distribution"))
